# Generated by Django 2.2.10 on 2020-02-09 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=14)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='(mm/dd/2019)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='(mm/dd/2019)')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_register.BookList')),
            ],
        ),
    ]
