# Generated by Django 2.2.10 on 2020-02-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date(mm/dd/2020)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date(mm/dd/2020)'),
        ),
    ]
