# Generated by Django 2.2.10 on 2020-02-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_register', '0004_bookorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookOrder',
        ),
    ]
